// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface AnimalPartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.AnimalPart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 animal_id = 2;</code>
   * @return The animalId.
   */
  int getAnimalId();

  /**
   * <code>string part_type = 3;</code>
   * @return The partType.
   */
  java.lang.String getPartType();
  /**
   * <code>string part_type = 3;</code>
   * @return The bytes for partType.
   */
  com.google.protobuf.ByteString
      getPartTypeBytes();

  /**
   * <code>double weight = 4;</code>
   * @return The weight.
   */
  double getWeight();
}
