// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string registration_number = 2;</code>
   * @return The registrationNumber.
   */
  java.lang.String getRegistrationNumber();
  /**
   * <code>string registration_number = 2;</code>
   * @return The bytes for registrationNumber.
   */
  com.google.protobuf.ByteString
      getRegistrationNumberBytes();

  /**
   * <code>double weight = 3;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>.google.protobuf.Timestamp arrival_time = 4;</code>
   * @return Whether the arrivalTime field is set.
   */
  boolean hasArrivalTime();
  /**
   * <code>.google.protobuf.Timestamp arrival_time = 4;</code>
   * @return The arrivalTime.
   */
  com.google.protobuf.Timestamp getArrivalTime();
  /**
   * <code>.google.protobuf.Timestamp arrival_time = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getArrivalTimeOrBuilder();
}
