// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateTrayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateTrayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
   * @return Whether the tray field is set.
   */
  boolean hasTray();
  /**
   * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
   * @return The tray.
   */
  com.slaughterhouse.grpc.Tray getTray();
  /**
   * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
   */
  com.slaughterhouse.grpc.TrayOrBuilder getTrayOrBuilder();

  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  com.slaughterhouse.grpc.Error getError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder();
}
