// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateAnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateAnimalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
   * @return Whether the animal field is set.
   */
  boolean hasAnimal();
  /**
   * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
   * @return The animal.
   */
  com.slaughterhouse.grpc.AnimalProto getAnimal();
  /**
   * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
   */
  com.slaughterhouse.grpc.AnimalProtoOrBuilder getAnimalOrBuilder();

  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  com.slaughterhouse.grpc.Error getError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder();
}
