// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

/**
 * Protobuf type {@code via.pro3.slaughterhouse.CreateTrayResponse}
 */
public final class CreateTrayResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:via.pro3.slaughterhouse.CreateTrayResponse)
    CreateTrayResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateTrayResponse.newBuilder() to construct.
  private CreateTrayResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateTrayResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateTrayResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateTrayResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.slaughterhouse.grpc.Tray.Builder subBuilder = null;
            if (tray_ != null) {
              subBuilder = tray_.toBuilder();
            }
            tray_ = input.readMessage(com.slaughterhouse.grpc.Tray.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tray_);
              tray_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.slaughterhouse.grpc.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.slaughterhouse.grpc.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateTrayResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.slaughterhouse.grpc.CreateTrayResponse.class, com.slaughterhouse.grpc.CreateTrayResponse.Builder.class);
  }

  public static final int TRAY_FIELD_NUMBER = 1;
  private com.slaughterhouse.grpc.Tray tray_;
  /**
   * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
   * @return Whether the tray field is set.
   */
  @java.lang.Override
  public boolean hasTray() {
    return tray_ != null;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
   * @return The tray.
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.Tray getTray() {
    return tray_ == null ? com.slaughterhouse.grpc.Tray.getDefaultInstance() : tray_;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.TrayOrBuilder getTrayOrBuilder() {
    return getTray();
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private com.slaughterhouse.grpc.Error error_;
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.Error getError() {
    return error_ == null ? com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tray_ != null) {
      output.writeMessage(1, getTray());
    }
    if (error_ != null) {
      output.writeMessage(2, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tray_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTray());
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.slaughterhouse.grpc.CreateTrayResponse)) {
      return super.equals(obj);
    }
    com.slaughterhouse.grpc.CreateTrayResponse other = (com.slaughterhouse.grpc.CreateTrayResponse) obj;

    if (hasTray() != other.hasTray()) return false;
    if (hasTray()) {
      if (!getTray()
          .equals(other.getTray())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTray()) {
      hash = (37 * hash) + TRAY_FIELD_NUMBER;
      hash = (53 * hash) + getTray().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateTrayResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.slaughterhouse.grpc.CreateTrayResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code via.pro3.slaughterhouse.CreateTrayResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:via.pro3.slaughterhouse.CreateTrayResponse)
      com.slaughterhouse.grpc.CreateTrayResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateTrayResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.slaughterhouse.grpc.CreateTrayResponse.class, com.slaughterhouse.grpc.CreateTrayResponse.Builder.class);
    }

    // Construct using com.slaughterhouse.grpc.CreateTrayResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (trayBuilder_ == null) {
        tray_ = null;
      } else {
        tray_ = null;
        trayBuilder_ = null;
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateTrayResponse getDefaultInstanceForType() {
      return com.slaughterhouse.grpc.CreateTrayResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateTrayResponse build() {
      com.slaughterhouse.grpc.CreateTrayResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateTrayResponse buildPartial() {
      com.slaughterhouse.grpc.CreateTrayResponse result = new com.slaughterhouse.grpc.CreateTrayResponse(this);
      if (trayBuilder_ == null) {
        result.tray_ = tray_;
      } else {
        result.tray_ = trayBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.slaughterhouse.grpc.CreateTrayResponse) {
        return mergeFrom((com.slaughterhouse.grpc.CreateTrayResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.slaughterhouse.grpc.CreateTrayResponse other) {
      if (other == com.slaughterhouse.grpc.CreateTrayResponse.getDefaultInstance()) return this;
      if (other.hasTray()) {
        mergeTray(other.getTray());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.slaughterhouse.grpc.CreateTrayResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.slaughterhouse.grpc.CreateTrayResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.slaughterhouse.grpc.Tray tray_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Tray, com.slaughterhouse.grpc.Tray.Builder, com.slaughterhouse.grpc.TrayOrBuilder> trayBuilder_;
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     * @return Whether the tray field is set.
     */
    public boolean hasTray() {
      return trayBuilder_ != null || tray_ != null;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     * @return The tray.
     */
    public com.slaughterhouse.grpc.Tray getTray() {
      if (trayBuilder_ == null) {
        return tray_ == null ? com.slaughterhouse.grpc.Tray.getDefaultInstance() : tray_;
      } else {
        return trayBuilder_.getMessage();
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     */
    public Builder setTray(com.slaughterhouse.grpc.Tray value) {
      if (trayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tray_ = value;
        onChanged();
      } else {
        trayBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     */
    public Builder setTray(
        com.slaughterhouse.grpc.Tray.Builder builderForValue) {
      if (trayBuilder_ == null) {
        tray_ = builderForValue.build();
        onChanged();
      } else {
        trayBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     */
    public Builder mergeTray(com.slaughterhouse.grpc.Tray value) {
      if (trayBuilder_ == null) {
        if (tray_ != null) {
          tray_ =
            com.slaughterhouse.grpc.Tray.newBuilder(tray_).mergeFrom(value).buildPartial();
        } else {
          tray_ = value;
        }
        onChanged();
      } else {
        trayBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     */
    public Builder clearTray() {
      if (trayBuilder_ == null) {
        tray_ = null;
        onChanged();
      } else {
        tray_ = null;
        trayBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     */
    public com.slaughterhouse.grpc.Tray.Builder getTrayBuilder() {
      
      onChanged();
      return getTrayFieldBuilder().getBuilder();
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     */
    public com.slaughterhouse.grpc.TrayOrBuilder getTrayOrBuilder() {
      if (trayBuilder_ != null) {
        return trayBuilder_.getMessageOrBuilder();
      } else {
        return tray_ == null ?
            com.slaughterhouse.grpc.Tray.getDefaultInstance() : tray_;
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Tray tray = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Tray, com.slaughterhouse.grpc.Tray.Builder, com.slaughterhouse.grpc.TrayOrBuilder> 
        getTrayFieldBuilder() {
      if (trayBuilder_ == null) {
        trayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.slaughterhouse.grpc.Tray, com.slaughterhouse.grpc.Tray.Builder, com.slaughterhouse.grpc.TrayOrBuilder>(
                getTray(),
                getParentForChildren(),
                isClean());
        tray_ = null;
      }
      return trayBuilder_;
    }

    private com.slaughterhouse.grpc.Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     * @return The error.
     */
    public com.slaughterhouse.grpc.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder setError(com.slaughterhouse.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder setError(
        com.slaughterhouse.grpc.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder mergeError(com.slaughterhouse.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.slaughterhouse.grpc.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public com.slaughterhouse.grpc.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:via.pro3.slaughterhouse.CreateTrayResponse)
  }

  // @@protoc_insertion_point(class_scope:via.pro3.slaughterhouse.CreateTrayResponse)
  private static final com.slaughterhouse.grpc.CreateTrayResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.slaughterhouse.grpc.CreateTrayResponse();
  }

  public static com.slaughterhouse.grpc.CreateTrayResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTrayResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateTrayResponse>() {
    @java.lang.Override
    public CreateTrayResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateTrayResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateTrayResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTrayResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.slaughterhouse.grpc.CreateTrayResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

