// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateAnimalPartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateAnimalPartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   * @return Whether the part field is set.
   */
  boolean hasPart();
  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   * @return The part.
   */
  com.slaughterhouse.grpc.AnimalPart getPart();
  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   */
  com.slaughterhouse.grpc.AnimalPartOrBuilder getPartOrBuilder();

  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  com.slaughterhouse.grpc.Error getError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder();
}
