// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateProductToPartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateProductToPartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
   * @return Whether the mapping field is set.
   */
  boolean hasMapping();
  /**
   * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
   * @return The mapping.
   */
  com.slaughterhouse.grpc.ProductToPart getMapping();
  /**
   * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
   */
  com.slaughterhouse.grpc.ProductToPartOrBuilder getMappingOrBuilder();
}
