// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateProductToPartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateProductToPartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.ProductToPartProto mapping = 1;</code>
   * @return Whether the mapping field is set.
   */
  boolean hasMapping();
  /**
   * <code>.via.pro3.slaughterhouse.ProductToPartProto mapping = 1;</code>
   * @return The mapping.
   */
  com.slaughterhouse.grpc.ProductToPartProto getMapping();
  /**
   * <code>.via.pro3.slaughterhouse.ProductToPartProto mapping = 1;</code>
   */
  com.slaughterhouse.grpc.ProductToPartProtoOrBuilder getMappingOrBuilder();

  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  com.slaughterhouse.grpc.Error getError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder();
}
