// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.Product product = 1;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.via.pro3.slaughterhouse.Product product = 1;</code>
   * @return The product.
   */
  com.slaughterhouse.grpc.Product getProduct();
  /**
   * <code>.via.pro3.slaughterhouse.Product product = 1;</code>
   */
  com.slaughterhouse.grpc.ProductOrBuilder getProductOrBuilder();
}
