// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

/**
 * Protobuf type {@code via.pro3.slaughterhouse.CreateProductToPartResponse}
 */
public final class CreateProductToPartResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:via.pro3.slaughterhouse.CreateProductToPartResponse)
    CreateProductToPartResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateProductToPartResponse.newBuilder() to construct.
  private CreateProductToPartResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateProductToPartResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateProductToPartResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateProductToPartResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.slaughterhouse.grpc.ProductToPart.Builder subBuilder = null;
            if (mapping_ != null) {
              subBuilder = mapping_.toBuilder();
            }
            mapping_ = input.readMessage(com.slaughterhouse.grpc.ProductToPart.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mapping_);
              mapping_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.slaughterhouse.grpc.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.slaughterhouse.grpc.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.slaughterhouse.grpc.CreateProductToPartResponse.class, com.slaughterhouse.grpc.CreateProductToPartResponse.Builder.class);
  }

  public static final int MAPPING_FIELD_NUMBER = 1;
  private com.slaughterhouse.grpc.ProductToPart mapping_;
  /**
   * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
   * @return Whether the mapping field is set.
   */
  @java.lang.Override
  public boolean hasMapping() {
    return mapping_ != null;
  }
  /**
   * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
   * @return The mapping.
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.ProductToPart getMapping() {
    return mapping_ == null ? com.slaughterhouse.grpc.ProductToPart.getDefaultInstance() : mapping_;
  }
  /**
   * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.ProductToPartOrBuilder getMappingOrBuilder() {
    return getMapping();
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private com.slaughterhouse.grpc.Error error_;
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.Error getError() {
    return error_ == null ? com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mapping_ != null) {
      output.writeMessage(1, getMapping());
    }
    if (error_ != null) {
      output.writeMessage(2, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mapping_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMapping());
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.slaughterhouse.grpc.CreateProductToPartResponse)) {
      return super.equals(obj);
    }
    com.slaughterhouse.grpc.CreateProductToPartResponse other = (com.slaughterhouse.grpc.CreateProductToPartResponse) obj;

    if (hasMapping() != other.hasMapping()) return false;
    if (hasMapping()) {
      if (!getMapping()
          .equals(other.getMapping())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMapping()) {
      hash = (37 * hash) + MAPPING_FIELD_NUMBER;
      hash = (53 * hash) + getMapping().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateProductToPartResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.slaughterhouse.grpc.CreateProductToPartResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code via.pro3.slaughterhouse.CreateProductToPartResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:via.pro3.slaughterhouse.CreateProductToPartResponse)
      com.slaughterhouse.grpc.CreateProductToPartResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.slaughterhouse.grpc.CreateProductToPartResponse.class, com.slaughterhouse.grpc.CreateProductToPartResponse.Builder.class);
    }

    // Construct using com.slaughterhouse.grpc.CreateProductToPartResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mappingBuilder_ == null) {
        mapping_ = null;
      } else {
        mapping_ = null;
        mappingBuilder_ = null;
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateProductToPartResponse getDefaultInstanceForType() {
      return com.slaughterhouse.grpc.CreateProductToPartResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateProductToPartResponse build() {
      com.slaughterhouse.grpc.CreateProductToPartResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateProductToPartResponse buildPartial() {
      com.slaughterhouse.grpc.CreateProductToPartResponse result = new com.slaughterhouse.grpc.CreateProductToPartResponse(this);
      if (mappingBuilder_ == null) {
        result.mapping_ = mapping_;
      } else {
        result.mapping_ = mappingBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.slaughterhouse.grpc.CreateProductToPartResponse) {
        return mergeFrom((com.slaughterhouse.grpc.CreateProductToPartResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.slaughterhouse.grpc.CreateProductToPartResponse other) {
      if (other == com.slaughterhouse.grpc.CreateProductToPartResponse.getDefaultInstance()) return this;
      if (other.hasMapping()) {
        mergeMapping(other.getMapping());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.slaughterhouse.grpc.CreateProductToPartResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.slaughterhouse.grpc.CreateProductToPartResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.slaughterhouse.grpc.ProductToPart mapping_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.ProductToPart, com.slaughterhouse.grpc.ProductToPart.Builder, com.slaughterhouse.grpc.ProductToPartOrBuilder> mappingBuilder_;
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     * @return Whether the mapping field is set.
     */
    public boolean hasMapping() {
      return mappingBuilder_ != null || mapping_ != null;
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     * @return The mapping.
     */
    public com.slaughterhouse.grpc.ProductToPart getMapping() {
      if (mappingBuilder_ == null) {
        return mapping_ == null ? com.slaughterhouse.grpc.ProductToPart.getDefaultInstance() : mapping_;
      } else {
        return mappingBuilder_.getMessage();
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     */
    public Builder setMapping(com.slaughterhouse.grpc.ProductToPart value) {
      if (mappingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mapping_ = value;
        onChanged();
      } else {
        mappingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     */
    public Builder setMapping(
        com.slaughterhouse.grpc.ProductToPart.Builder builderForValue) {
      if (mappingBuilder_ == null) {
        mapping_ = builderForValue.build();
        onChanged();
      } else {
        mappingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     */
    public Builder mergeMapping(com.slaughterhouse.grpc.ProductToPart value) {
      if (mappingBuilder_ == null) {
        if (mapping_ != null) {
          mapping_ =
            com.slaughterhouse.grpc.ProductToPart.newBuilder(mapping_).mergeFrom(value).buildPartial();
        } else {
          mapping_ = value;
        }
        onChanged();
      } else {
        mappingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     */
    public Builder clearMapping() {
      if (mappingBuilder_ == null) {
        mapping_ = null;
        onChanged();
      } else {
        mapping_ = null;
        mappingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     */
    public com.slaughterhouse.grpc.ProductToPart.Builder getMappingBuilder() {
      
      onChanged();
      return getMappingFieldBuilder().getBuilder();
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     */
    public com.slaughterhouse.grpc.ProductToPartOrBuilder getMappingOrBuilder() {
      if (mappingBuilder_ != null) {
        return mappingBuilder_.getMessageOrBuilder();
      } else {
        return mapping_ == null ?
            com.slaughterhouse.grpc.ProductToPart.getDefaultInstance() : mapping_;
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.ProductToPart mapping = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.ProductToPart, com.slaughterhouse.grpc.ProductToPart.Builder, com.slaughterhouse.grpc.ProductToPartOrBuilder> 
        getMappingFieldBuilder() {
      if (mappingBuilder_ == null) {
        mappingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.slaughterhouse.grpc.ProductToPart, com.slaughterhouse.grpc.ProductToPart.Builder, com.slaughterhouse.grpc.ProductToPartOrBuilder>(
                getMapping(),
                getParentForChildren(),
                isClean());
        mapping_ = null;
      }
      return mappingBuilder_;
    }

    private com.slaughterhouse.grpc.Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     * @return The error.
     */
    public com.slaughterhouse.grpc.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder setError(com.slaughterhouse.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder setError(
        com.slaughterhouse.grpc.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder mergeError(com.slaughterhouse.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.slaughterhouse.grpc.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public com.slaughterhouse.grpc.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:via.pro3.slaughterhouse.CreateProductToPartResponse)
  }

  // @@protoc_insertion_point(class_scope:via.pro3.slaughterhouse.CreateProductToPartResponse)
  private static final com.slaughterhouse.grpc.CreateProductToPartResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.slaughterhouse.grpc.CreateProductToPartResponse();
  }

  public static com.slaughterhouse.grpc.CreateProductToPartResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateProductToPartResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateProductToPartResponse>() {
    @java.lang.Override
    public CreateProductToPartResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateProductToPartResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateProductToPartResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateProductToPartResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.slaughterhouse.grpc.CreateProductToPartResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

