// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateAnimalPartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateAnimalPartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   * @return Whether the part field is set.
   */
  boolean hasPart();
  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   * @return The part.
   */
  com.slaughterhouse.grpc.AnimalPart getPart();
  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   */
  com.slaughterhouse.grpc.AnimalPartOrBuilder getPartOrBuilder();
}
