// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

/**
 * Protobuf type {@code via.pro3.slaughterhouse.CreateAnimalResponse}
 */
public final class CreateAnimalResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:via.pro3.slaughterhouse.CreateAnimalResponse)
    CreateAnimalResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAnimalResponse.newBuilder() to construct.
  private CreateAnimalResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAnimalResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateAnimalResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateAnimalResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.slaughterhouse.grpc.AnimalProto.Builder subBuilder = null;
            if (animal_ != null) {
              subBuilder = animal_.toBuilder();
            }
            animal_ = input.readMessage(com.slaughterhouse.grpc.AnimalProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(animal_);
              animal_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.slaughterhouse.grpc.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.slaughterhouse.grpc.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.slaughterhouse.grpc.CreateAnimalResponse.class, com.slaughterhouse.grpc.CreateAnimalResponse.Builder.class);
  }

  public static final int ANIMAL_FIELD_NUMBER = 1;
  private com.slaughterhouse.grpc.AnimalProto animal_;
  /**
   * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
   * @return Whether the animal field is set.
   */
  @java.lang.Override
  public boolean hasAnimal() {
    return animal_ != null;
  }
  /**
   * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
   * @return The animal.
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.AnimalProto getAnimal() {
    return animal_ == null ? com.slaughterhouse.grpc.AnimalProto.getDefaultInstance() : animal_;
  }
  /**
   * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.AnimalProtoOrBuilder getAnimalOrBuilder() {
    return getAnimal();
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private com.slaughterhouse.grpc.Error error_;
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.Error getError() {
    return error_ == null ? com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (animal_ != null) {
      output.writeMessage(1, getAnimal());
    }
    if (error_ != null) {
      output.writeMessage(2, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (animal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAnimal());
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.slaughterhouse.grpc.CreateAnimalResponse)) {
      return super.equals(obj);
    }
    com.slaughterhouse.grpc.CreateAnimalResponse other = (com.slaughterhouse.grpc.CreateAnimalResponse) obj;

    if (hasAnimal() != other.hasAnimal()) return false;
    if (hasAnimal()) {
      if (!getAnimal()
          .equals(other.getAnimal())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAnimal()) {
      hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getAnimal().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateAnimalResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.slaughterhouse.grpc.CreateAnimalResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code via.pro3.slaughterhouse.CreateAnimalResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:via.pro3.slaughterhouse.CreateAnimalResponse)
      com.slaughterhouse.grpc.CreateAnimalResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.slaughterhouse.grpc.CreateAnimalResponse.class, com.slaughterhouse.grpc.CreateAnimalResponse.Builder.class);
    }

    // Construct using com.slaughterhouse.grpc.CreateAnimalResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (animalBuilder_ == null) {
        animal_ = null;
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateAnimalResponse getDefaultInstanceForType() {
      return com.slaughterhouse.grpc.CreateAnimalResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateAnimalResponse build() {
      com.slaughterhouse.grpc.CreateAnimalResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateAnimalResponse buildPartial() {
      com.slaughterhouse.grpc.CreateAnimalResponse result = new com.slaughterhouse.grpc.CreateAnimalResponse(this);
      if (animalBuilder_ == null) {
        result.animal_ = animal_;
      } else {
        result.animal_ = animalBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.slaughterhouse.grpc.CreateAnimalResponse) {
        return mergeFrom((com.slaughterhouse.grpc.CreateAnimalResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.slaughterhouse.grpc.CreateAnimalResponse other) {
      if (other == com.slaughterhouse.grpc.CreateAnimalResponse.getDefaultInstance()) return this;
      if (other.hasAnimal()) {
        mergeAnimal(other.getAnimal());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.slaughterhouse.grpc.CreateAnimalResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.slaughterhouse.grpc.CreateAnimalResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.slaughterhouse.grpc.AnimalProto animal_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.AnimalProto, com.slaughterhouse.grpc.AnimalProto.Builder, com.slaughterhouse.grpc.AnimalProtoOrBuilder> animalBuilder_;
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     * @return Whether the animal field is set.
     */
    public boolean hasAnimal() {
      return animalBuilder_ != null || animal_ != null;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     * @return The animal.
     */
    public com.slaughterhouse.grpc.AnimalProto getAnimal() {
      if (animalBuilder_ == null) {
        return animal_ == null ? com.slaughterhouse.grpc.AnimalProto.getDefaultInstance() : animal_;
      } else {
        return animalBuilder_.getMessage();
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     */
    public Builder setAnimal(com.slaughterhouse.grpc.AnimalProto value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        animal_ = value;
        onChanged();
      } else {
        animalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     */
    public Builder setAnimal(
        com.slaughterhouse.grpc.AnimalProto.Builder builderForValue) {
      if (animalBuilder_ == null) {
        animal_ = builderForValue.build();
        onChanged();
      } else {
        animalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     */
    public Builder mergeAnimal(com.slaughterhouse.grpc.AnimalProto value) {
      if (animalBuilder_ == null) {
        if (animal_ != null) {
          animal_ =
            com.slaughterhouse.grpc.AnimalProto.newBuilder(animal_).mergeFrom(value).buildPartial();
        } else {
          animal_ = value;
        }
        onChanged();
      } else {
        animalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     */
    public Builder clearAnimal() {
      if (animalBuilder_ == null) {
        animal_ = null;
        onChanged();
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     */
    public com.slaughterhouse.grpc.AnimalProto.Builder getAnimalBuilder() {
      
      onChanged();
      return getAnimalFieldBuilder().getBuilder();
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     */
    public com.slaughterhouse.grpc.AnimalProtoOrBuilder getAnimalOrBuilder() {
      if (animalBuilder_ != null) {
        return animalBuilder_.getMessageOrBuilder();
      } else {
        return animal_ == null ?
            com.slaughterhouse.grpc.AnimalProto.getDefaultInstance() : animal_;
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalProto animal = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.AnimalProto, com.slaughterhouse.grpc.AnimalProto.Builder, com.slaughterhouse.grpc.AnimalProtoOrBuilder> 
        getAnimalFieldBuilder() {
      if (animalBuilder_ == null) {
        animalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.slaughterhouse.grpc.AnimalProto, com.slaughterhouse.grpc.AnimalProto.Builder, com.slaughterhouse.grpc.AnimalProtoOrBuilder>(
                getAnimal(),
                getParentForChildren(),
                isClean());
        animal_ = null;
      }
      return animalBuilder_;
    }

    private com.slaughterhouse.grpc.Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     * @return The error.
     */
    public com.slaughterhouse.grpc.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder setError(com.slaughterhouse.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder setError(
        com.slaughterhouse.grpc.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder mergeError(com.slaughterhouse.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.slaughterhouse.grpc.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public com.slaughterhouse.grpc.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    public com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.slaughterhouse.grpc.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.slaughterhouse.grpc.Error, com.slaughterhouse.grpc.Error.Builder, com.slaughterhouse.grpc.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:via.pro3.slaughterhouse.CreateAnimalResponse)
  }

  // @@protoc_insertion_point(class_scope:via.pro3.slaughterhouse.CreateAnimalResponse)
  private static final com.slaughterhouse.grpc.CreateAnimalResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.slaughterhouse.grpc.CreateAnimalResponse();
  }

  public static com.slaughterhouse.grpc.CreateAnimalResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAnimalResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateAnimalResponse>() {
    @java.lang.Override
    public CreateAnimalResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateAnimalResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateAnimalResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAnimalResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.slaughterhouse.grpc.CreateAnimalResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

