// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface CreateProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.CreateProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.ProductProto product = 1;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.via.pro3.slaughterhouse.ProductProto product = 1;</code>
   * @return The product.
   */
  com.slaughterhouse.grpc.ProductProto getProduct();
  /**
   * <code>.via.pro3.slaughterhouse.ProductProto product = 1;</code>
   */
  com.slaughterhouse.grpc.ProductProtoOrBuilder getProductOrBuilder();

  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   * @return The error.
   */
  com.slaughterhouse.grpc.Error getError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 2;</code>
   */
  com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder();
}
