// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

/**
 * Protobuf type {@code via.pro3.slaughterhouse.CreateAnimalPartRequest}
 */
public final class CreateAnimalPartRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:via.pro3.slaughterhouse.CreateAnimalPartRequest)
    CreateAnimalPartRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAnimalPartRequest.newBuilder() to construct.
  private CreateAnimalPartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAnimalPartRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateAnimalPartRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateAnimalPartRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.slaughterhouse.grpc.AnimalPart.Builder subBuilder = null;
            if (part_ != null) {
              subBuilder = part_.toBuilder();
            }
            part_ = input.readMessage(com.slaughterhouse.grpc.AnimalPart.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(part_);
              part_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.slaughterhouse.grpc.CreateAnimalPartRequest.class, com.slaughterhouse.grpc.CreateAnimalPartRequest.Builder.class);
  }

  public static final int PART_FIELD_NUMBER = 1;
  private com.slaughterhouse.grpc.AnimalPart part_;
  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   * @return Whether the part field is set.
   */
  @java.lang.Override
  public boolean hasPart() {
    return part_ != null;
  }
  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   * @return The part.
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.AnimalPart getPart() {
    return part_ == null ? com.slaughterhouse.grpc.AnimalPart.getDefaultInstance() : part_;
  }
  /**
   * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.AnimalPartOrBuilder getPartOrBuilder() {
    return getPart();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (part_ != null) {
      output.writeMessage(1, getPart());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (part_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPart());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.slaughterhouse.grpc.CreateAnimalPartRequest)) {
      return super.equals(obj);
    }
    com.slaughterhouse.grpc.CreateAnimalPartRequest other = (com.slaughterhouse.grpc.CreateAnimalPartRequest) obj;

    if (hasPart() != other.hasPart()) return false;
    if (hasPart()) {
      if (!getPart()
          .equals(other.getPart())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPart()) {
      hash = (37 * hash) + PART_FIELD_NUMBER;
      hash = (53 * hash) + getPart().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.CreateAnimalPartRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.slaughterhouse.grpc.CreateAnimalPartRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code via.pro3.slaughterhouse.CreateAnimalPartRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:via.pro3.slaughterhouse.CreateAnimalPartRequest)
      com.slaughterhouse.grpc.CreateAnimalPartRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.slaughterhouse.grpc.CreateAnimalPartRequest.class, com.slaughterhouse.grpc.CreateAnimalPartRequest.Builder.class);
    }

    // Construct using com.slaughterhouse.grpc.CreateAnimalPartRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (partBuilder_ == null) {
        part_ = null;
      } else {
        part_ = null;
        partBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateAnimalPartRequest getDefaultInstanceForType() {
      return com.slaughterhouse.grpc.CreateAnimalPartRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateAnimalPartRequest build() {
      com.slaughterhouse.grpc.CreateAnimalPartRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.CreateAnimalPartRequest buildPartial() {
      com.slaughterhouse.grpc.CreateAnimalPartRequest result = new com.slaughterhouse.grpc.CreateAnimalPartRequest(this);
      if (partBuilder_ == null) {
        result.part_ = part_;
      } else {
        result.part_ = partBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.slaughterhouse.grpc.CreateAnimalPartRequest) {
        return mergeFrom((com.slaughterhouse.grpc.CreateAnimalPartRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.slaughterhouse.grpc.CreateAnimalPartRequest other) {
      if (other == com.slaughterhouse.grpc.CreateAnimalPartRequest.getDefaultInstance()) return this;
      if (other.hasPart()) {
        mergePart(other.getPart());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.slaughterhouse.grpc.CreateAnimalPartRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.slaughterhouse.grpc.CreateAnimalPartRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.slaughterhouse.grpc.AnimalPart part_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.AnimalPart, com.slaughterhouse.grpc.AnimalPart.Builder, com.slaughterhouse.grpc.AnimalPartOrBuilder> partBuilder_;
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     * @return Whether the part field is set.
     */
    public boolean hasPart() {
      return partBuilder_ != null || part_ != null;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     * @return The part.
     */
    public com.slaughterhouse.grpc.AnimalPart getPart() {
      if (partBuilder_ == null) {
        return part_ == null ? com.slaughterhouse.grpc.AnimalPart.getDefaultInstance() : part_;
      } else {
        return partBuilder_.getMessage();
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     */
    public Builder setPart(com.slaughterhouse.grpc.AnimalPart value) {
      if (partBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        part_ = value;
        onChanged();
      } else {
        partBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     */
    public Builder setPart(
        com.slaughterhouse.grpc.AnimalPart.Builder builderForValue) {
      if (partBuilder_ == null) {
        part_ = builderForValue.build();
        onChanged();
      } else {
        partBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     */
    public Builder mergePart(com.slaughterhouse.grpc.AnimalPart value) {
      if (partBuilder_ == null) {
        if (part_ != null) {
          part_ =
            com.slaughterhouse.grpc.AnimalPart.newBuilder(part_).mergeFrom(value).buildPartial();
        } else {
          part_ = value;
        }
        onChanged();
      } else {
        partBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     */
    public Builder clearPart() {
      if (partBuilder_ == null) {
        part_ = null;
        onChanged();
      } else {
        part_ = null;
        partBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     */
    public com.slaughterhouse.grpc.AnimalPart.Builder getPartBuilder() {
      
      onChanged();
      return getPartFieldBuilder().getBuilder();
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     */
    public com.slaughterhouse.grpc.AnimalPartOrBuilder getPartOrBuilder() {
      if (partBuilder_ != null) {
        return partBuilder_.getMessageOrBuilder();
      } else {
        return part_ == null ?
            com.slaughterhouse.grpc.AnimalPart.getDefaultInstance() : part_;
      }
    }
    /**
     * <code>.via.pro3.slaughterhouse.AnimalPart part = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.slaughterhouse.grpc.AnimalPart, com.slaughterhouse.grpc.AnimalPart.Builder, com.slaughterhouse.grpc.AnimalPartOrBuilder> 
        getPartFieldBuilder() {
      if (partBuilder_ == null) {
        partBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.slaughterhouse.grpc.AnimalPart, com.slaughterhouse.grpc.AnimalPart.Builder, com.slaughterhouse.grpc.AnimalPartOrBuilder>(
                getPart(),
                getParentForChildren(),
                isClean());
        part_ = null;
      }
      return partBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:via.pro3.slaughterhouse.CreateAnimalPartRequest)
  }

  // @@protoc_insertion_point(class_scope:via.pro3.slaughterhouse.CreateAnimalPartRequest)
  private static final com.slaughterhouse.grpc.CreateAnimalPartRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.slaughterhouse.grpc.CreateAnimalPartRequest();
  }

  public static com.slaughterhouse.grpc.CreateAnimalPartRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAnimalPartRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateAnimalPartRequest>() {
    @java.lang.Override
    public CreateAnimalPartRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateAnimalPartRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateAnimalPartRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAnimalPartRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.slaughterhouse.grpc.CreateAnimalPartRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

