// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface DeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.DeleteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.via.pro3.slaughterhouse.Error error = 1;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 1;</code>
   * @return The error.
   */
  com.slaughterhouse.grpc.Error getError();
  /**
   * <code>.via.pro3.slaughterhouse.Error error = 1;</code>
   */
  com.slaughterhouse.grpc.ErrorOrBuilder getErrorOrBuilder();
}
