// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface ListAnimalsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.ListAnimalsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalProto animals = 1;</code>
   */
  java.util.List<com.slaughterhouse.grpc.AnimalProto> 
      getAnimalsList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalProto animals = 1;</code>
   */
  com.slaughterhouse.grpc.AnimalProto getAnimals(int index);
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalProto animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalProto animals = 1;</code>
   */
  java.util.List<? extends com.slaughterhouse.grpc.AnimalProtoOrBuilder> 
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalProto animals = 1;</code>
   */
  com.slaughterhouse.grpc.AnimalProtoOrBuilder getAnimalsOrBuilder(
      int index);
}
