// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface ListAnimalPartsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.ListAnimalPartsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalPart parts = 1;</code>
   */
  java.util.List<com.slaughterhouse.grpc.AnimalPart> 
      getPartsList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalPart parts = 1;</code>
   */
  com.slaughterhouse.grpc.AnimalPart getParts(int index);
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalPart parts = 1;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalPart parts = 1;</code>
   */
  java.util.List<? extends com.slaughterhouse.grpc.AnimalPartOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.AnimalPart parts = 1;</code>
   */
  com.slaughterhouse.grpc.AnimalPartOrBuilder getPartsOrBuilder(
      int index);
}
