// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

/**
 * Protobuf type {@code via.pro3.slaughterhouse.ListProductToPartResponse}
 */
public final class ListProductToPartResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:via.pro3.slaughterhouse.ListProductToPartResponse)
    ListProductToPartResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListProductToPartResponse.newBuilder() to construct.
  private ListProductToPartResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListProductToPartResponse() {
    mappings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListProductToPartResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListProductToPartResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              mappings_ = new java.util.ArrayList<com.slaughterhouse.grpc.ProductToPart>();
              mutable_bitField0_ |= 0x00000001;
            }
            mappings_.add(
                input.readMessage(com.slaughterhouse.grpc.ProductToPart.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        mappings_ = java.util.Collections.unmodifiableList(mappings_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.slaughterhouse.grpc.ListProductToPartResponse.class, com.slaughterhouse.grpc.ListProductToPartResponse.Builder.class);
  }

  public static final int MAPPINGS_FIELD_NUMBER = 1;
  private java.util.List<com.slaughterhouse.grpc.ProductToPart> mappings_;
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.slaughterhouse.grpc.ProductToPart> getMappingsList() {
    return mappings_;
  }
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.slaughterhouse.grpc.ProductToPartOrBuilder> 
      getMappingsOrBuilderList() {
    return mappings_;
  }
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
   */
  @java.lang.Override
  public int getMappingsCount() {
    return mappings_.size();
  }
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.ProductToPart getMappings(int index) {
    return mappings_.get(index);
  }
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
   */
  @java.lang.Override
  public com.slaughterhouse.grpc.ProductToPartOrBuilder getMappingsOrBuilder(
      int index) {
    return mappings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < mappings_.size(); i++) {
      output.writeMessage(1, mappings_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < mappings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, mappings_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.slaughterhouse.grpc.ListProductToPartResponse)) {
      return super.equals(obj);
    }
    com.slaughterhouse.grpc.ListProductToPartResponse other = (com.slaughterhouse.grpc.ListProductToPartResponse) obj;

    if (!getMappingsList()
        .equals(other.getMappingsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMappingsCount() > 0) {
      hash = (37 * hash) + MAPPINGS_FIELD_NUMBER;
      hash = (53 * hash) + getMappingsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.slaughterhouse.grpc.ListProductToPartResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.slaughterhouse.grpc.ListProductToPartResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code via.pro3.slaughterhouse.ListProductToPartResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:via.pro3.slaughterhouse.ListProductToPartResponse)
      com.slaughterhouse.grpc.ListProductToPartResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.slaughterhouse.grpc.ListProductToPartResponse.class, com.slaughterhouse.grpc.ListProductToPartResponse.Builder.class);
    }

    // Construct using com.slaughterhouse.grpc.ListProductToPartResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMappingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mappingsBuilder_ == null) {
        mappings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        mappingsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.slaughterhouse.grpc.SlaughterhouseProto.internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.ListProductToPartResponse getDefaultInstanceForType() {
      return com.slaughterhouse.grpc.ListProductToPartResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.ListProductToPartResponse build() {
      com.slaughterhouse.grpc.ListProductToPartResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.slaughterhouse.grpc.ListProductToPartResponse buildPartial() {
      com.slaughterhouse.grpc.ListProductToPartResponse result = new com.slaughterhouse.grpc.ListProductToPartResponse(this);
      int from_bitField0_ = bitField0_;
      if (mappingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          mappings_ = java.util.Collections.unmodifiableList(mappings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.mappings_ = mappings_;
      } else {
        result.mappings_ = mappingsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.slaughterhouse.grpc.ListProductToPartResponse) {
        return mergeFrom((com.slaughterhouse.grpc.ListProductToPartResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.slaughterhouse.grpc.ListProductToPartResponse other) {
      if (other == com.slaughterhouse.grpc.ListProductToPartResponse.getDefaultInstance()) return this;
      if (mappingsBuilder_ == null) {
        if (!other.mappings_.isEmpty()) {
          if (mappings_.isEmpty()) {
            mappings_ = other.mappings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMappingsIsMutable();
            mappings_.addAll(other.mappings_);
          }
          onChanged();
        }
      } else {
        if (!other.mappings_.isEmpty()) {
          if (mappingsBuilder_.isEmpty()) {
            mappingsBuilder_.dispose();
            mappingsBuilder_ = null;
            mappings_ = other.mappings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            mappingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMappingsFieldBuilder() : null;
          } else {
            mappingsBuilder_.addAllMessages(other.mappings_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.slaughterhouse.grpc.ListProductToPartResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.slaughterhouse.grpc.ListProductToPartResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.slaughterhouse.grpc.ProductToPart> mappings_ =
      java.util.Collections.emptyList();
    private void ensureMappingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        mappings_ = new java.util.ArrayList<com.slaughterhouse.grpc.ProductToPart>(mappings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.slaughterhouse.grpc.ProductToPart, com.slaughterhouse.grpc.ProductToPart.Builder, com.slaughterhouse.grpc.ProductToPartOrBuilder> mappingsBuilder_;

    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public java.util.List<com.slaughterhouse.grpc.ProductToPart> getMappingsList() {
      if (mappingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mappings_);
      } else {
        return mappingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public int getMappingsCount() {
      if (mappingsBuilder_ == null) {
        return mappings_.size();
      } else {
        return mappingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public com.slaughterhouse.grpc.ProductToPart getMappings(int index) {
      if (mappingsBuilder_ == null) {
        return mappings_.get(index);
      } else {
        return mappingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder setMappings(
        int index, com.slaughterhouse.grpc.ProductToPart value) {
      if (mappingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMappingsIsMutable();
        mappings_.set(index, value);
        onChanged();
      } else {
        mappingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder setMappings(
        int index, com.slaughterhouse.grpc.ProductToPart.Builder builderForValue) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.set(index, builderForValue.build());
        onChanged();
      } else {
        mappingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder addMappings(com.slaughterhouse.grpc.ProductToPart value) {
      if (mappingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMappingsIsMutable();
        mappings_.add(value);
        onChanged();
      } else {
        mappingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder addMappings(
        int index, com.slaughterhouse.grpc.ProductToPart value) {
      if (mappingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMappingsIsMutable();
        mappings_.add(index, value);
        onChanged();
      } else {
        mappingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder addMappings(
        com.slaughterhouse.grpc.ProductToPart.Builder builderForValue) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.add(builderForValue.build());
        onChanged();
      } else {
        mappingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder addMappings(
        int index, com.slaughterhouse.grpc.ProductToPart.Builder builderForValue) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.add(index, builderForValue.build());
        onChanged();
      } else {
        mappingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder addAllMappings(
        java.lang.Iterable<? extends com.slaughterhouse.grpc.ProductToPart> values) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mappings_);
        onChanged();
      } else {
        mappingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder clearMappings() {
      if (mappingsBuilder_ == null) {
        mappings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        mappingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public Builder removeMappings(int index) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.remove(index);
        onChanged();
      } else {
        mappingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public com.slaughterhouse.grpc.ProductToPart.Builder getMappingsBuilder(
        int index) {
      return getMappingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public com.slaughterhouse.grpc.ProductToPartOrBuilder getMappingsOrBuilder(
        int index) {
      if (mappingsBuilder_ == null) {
        return mappings_.get(index);  } else {
        return mappingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public java.util.List<? extends com.slaughterhouse.grpc.ProductToPartOrBuilder> 
         getMappingsOrBuilderList() {
      if (mappingsBuilder_ != null) {
        return mappingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mappings_);
      }
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public com.slaughterhouse.grpc.ProductToPart.Builder addMappingsBuilder() {
      return getMappingsFieldBuilder().addBuilder(
          com.slaughterhouse.grpc.ProductToPart.getDefaultInstance());
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public com.slaughterhouse.grpc.ProductToPart.Builder addMappingsBuilder(
        int index) {
      return getMappingsFieldBuilder().addBuilder(
          index, com.slaughterhouse.grpc.ProductToPart.getDefaultInstance());
    }
    /**
     * <code>repeated .via.pro3.slaughterhouse.ProductToPart mappings = 1;</code>
     */
    public java.util.List<com.slaughterhouse.grpc.ProductToPart.Builder> 
         getMappingsBuilderList() {
      return getMappingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.slaughterhouse.grpc.ProductToPart, com.slaughterhouse.grpc.ProductToPart.Builder, com.slaughterhouse.grpc.ProductToPartOrBuilder> 
        getMappingsFieldBuilder() {
      if (mappingsBuilder_ == null) {
        mappingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.slaughterhouse.grpc.ProductToPart, com.slaughterhouse.grpc.ProductToPart.Builder, com.slaughterhouse.grpc.ProductToPartOrBuilder>(
                mappings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        mappings_ = null;
      }
      return mappingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:via.pro3.slaughterhouse.ListProductToPartResponse)
  }

  // @@protoc_insertion_point(class_scope:via.pro3.slaughterhouse.ListProductToPartResponse)
  private static final com.slaughterhouse.grpc.ListProductToPartResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.slaughterhouse.grpc.ListProductToPartResponse();
  }

  public static com.slaughterhouse.grpc.ListProductToPartResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListProductToPartResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListProductToPartResponse>() {
    @java.lang.Override
    public ListProductToPartResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListProductToPartResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListProductToPartResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListProductToPartResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.slaughterhouse.grpc.ListProductToPartResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

