// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface ListProductsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.ListProductsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .via.pro3.slaughterhouse.Product products = 1;</code>
   */
  java.util.List<com.slaughterhouse.grpc.Product> 
      getProductsList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.Product products = 1;</code>
   */
  com.slaughterhouse.grpc.Product getProducts(int index);
  /**
   * <code>repeated .via.pro3.slaughterhouse.Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .via.pro3.slaughterhouse.Product products = 1;</code>
   */
  java.util.List<? extends com.slaughterhouse.grpc.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.Product products = 1;</code>
   */
  com.slaughterhouse.grpc.ProductOrBuilder getProductsOrBuilder(
      int index);
}
