// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface ListProductToPartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.ListProductToPartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPartProto mappings = 1;</code>
   */
  java.util.List<com.slaughterhouse.grpc.ProductToPartProto> 
      getMappingsList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPartProto mappings = 1;</code>
   */
  com.slaughterhouse.grpc.ProductToPartProto getMappings(int index);
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPartProto mappings = 1;</code>
   */
  int getMappingsCount();
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPartProto mappings = 1;</code>
   */
  java.util.List<? extends com.slaughterhouse.grpc.ProductToPartProtoOrBuilder> 
      getMappingsOrBuilderList();
  /**
   * <code>repeated .via.pro3.slaughterhouse.ProductToPartProto mappings = 1;</code>
   */
  com.slaughterhouse.grpc.ProductToPartProtoOrBuilder getMappingsOrBuilder(
      int index);
}
