// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public interface ProductToPartProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.pro3.slaughterhouse.ProductToPartProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 product_id = 2;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>int32 part_id = 3;</code>
   * @return The partId.
   */
  int getPartId();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();
}
