// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public final class SlaughterhouseProto {
  private SlaughterhouseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_AnimalPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_AnimalPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_Tray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_Tray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ProductToPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ProductToPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_GetByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_GetByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListTraysResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListTraysResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListProductsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListProductsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024slaughterhouse.proto\022\027via.pro3.slaught" +
      "erhouse\032\037google/protobuf/timestamp.proto" +
      "\032\033google/protobuf/empty.proto\"s\n\006Animal\022" +
      "\n\n\002id\030\001 \001(\003\022\033\n\023registration_number\030\002 \001(\t" +
      "\022\016\n\006weight\030\003 \001(\001\0220\n\014arrival_time\030\004 \001(\0132\032" +
      ".google.protobuf.Timestamp\"N\n\nAnimalPart" +
      "\022\n\n\002id\030\001 \001(\005\022\021\n\tanimal_id\030\002 \001(\005\022\021\n\tpart_" +
      "type\030\003 \001(\t\022\016\n\006weight\030\004 \001(\001\"9\n\004Tray\022\n\n\002id" +
      "\030\001 \001(\005\022\021\n\tpart_type\030\002 \001(\t\022\022\n\nmax_weight\030" +
      "\003 \001(\001\"8\n\007Product\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001" +
      "(\t\022\023\n\013description\030\003 \001(\t\"R\n\rProductToPart" +
      "\022\n\n\002id\030\001 \001(\005\022\022\n\nproduct_id\030\002 \001(\005\022\017\n\007part" +
      "_id\030\003 \001(\005\022\020\n\010quantity\030\004 \001(\005\"&\n\005Error\022\014\n\004" +
      "code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"\034\n\016GetByIdRe" +
      "quest\022\n\n\002id\030\001 \001(\005\"\037\n\021DeleteByIdRequest\022\n" +
      "\n\002id\030\001 \001(\005\"?\n\016DeleteResponse\022-\n\005error\030\001 " +
      "\001(\0132\036.via.pro3.slaughterhouse.Error\"F\n\023C" +
      "reateAnimalRequest\022/\n\006animal\030\001 \001(\0132\037.via" +
      ".pro3.slaughterhouse.Animal\"v\n\024CreateAni" +
      "malResponse\022/\n\006animal\030\001 \001(\0132\037.via.pro3.s" +
      "laughterhouse.Animal\022-\n\005error\030\002 \001(\0132\036.vi" +
      "a.pro3.slaughterhouse.Error\"G\n\023ListAnima" +
      "lsResponse\0220\n\007animals\030\001 \003(\0132\037.via.pro3.s" +
      "laughterhouse.Animal\"L\n\027CreateAnimalPart" +
      "Request\0221\n\004part\030\001 \001(\0132#.via.pro3.slaught" +
      "erhouse.AnimalPart\"|\n\030CreateAnimalPartRe" +
      "sponse\0221\n\004part\030\001 \001(\0132#.via.pro3.slaughte" +
      "rhouse.AnimalPart\022-\n\005error\030\002 \001(\0132\036.via.p" +
      "ro3.slaughterhouse.Error\"M\n\027ListAnimalPa" +
      "rtsResponse\0222\n\005parts\030\001 \003(\0132#.via.pro3.sl" +
      "aughterhouse.AnimalPart\"@\n\021CreateTrayReq" +
      "uest\022+\n\004tray\030\001 \001(\0132\035.via.pro3.slaughterh" +
      "ouse.Tray\"p\n\022CreateTrayResponse\022+\n\004tray\030" +
      "\001 \001(\0132\035.via.pro3.slaughterhouse.Tray\022-\n\005" +
      "error\030\002 \001(\0132\036.via.pro3.slaughterhouse.Er" +
      "ror\"A\n\021ListTraysResponse\022,\n\005trays\030\001 \003(\0132" +
      "\035.via.pro3.slaughterhouse.Tray\"I\n\024Create" +
      "ProductRequest\0221\n\007product\030\001 \001(\0132 .via.pr" +
      "o3.slaughterhouse.Product\"y\n\025CreateProdu" +
      "ctResponse\0221\n\007product\030\001 \001(\0132 .via.pro3.s" +
      "laughterhouse.Product\022-\n\005error\030\002 \001(\0132\036.v" +
      "ia.pro3.slaughterhouse.Error\"J\n\024ListProd" +
      "uctsResponse\0222\n\010products\030\001 \003(\0132 .via.pro" +
      "3.slaughterhouse.Product\"U\n\032CreateProduc" +
      "tToPartRequest\0227\n\007mapping\030\001 \001(\0132&.via.pr" +
      "o3.slaughterhouse.ProductToPart\"\205\001\n\033Crea" +
      "teProductToPartResponse\0227\n\007mapping\030\001 \001(\013" +
      "2&.via.pro3.slaughterhouse.ProductToPart" +
      "\022-\n\005error\030\002 \001(\0132\036.via.pro3.slaughterhous" +
      "e.Error\"U\n\031ListProductToPartResponse\0228\n\010" +
      "mappings\030\001 \003(\0132&.via.pro3.slaughterhouse" +
      ".ProductToPart2\215\003\n\rAnimalService\022k\n\014Crea" +
      "teAnimal\022,.via.pro3.slaughterhouse.Creat" +
      "eAnimalRequest\032-.via.pro3.slaughterhouse" +
      ".CreateAnimalResponse\022U\n\tGetAnimal\022\'.via" +
      ".pro3.slaughterhouse.GetByIdRequest\032\037.vi" +
      "a.pro3.slaughterhouse.Animal\022c\n\014DeleteAn" +
      "imal\022*.via.pro3.slaughterhouse.DeleteByI" +
      "dRequest\032\'.via.pro3.slaughterhouse.Delet" +
      "eResponse\022S\n\013ListAnimals\022\026.google.protob" +
      "uf.Empty\032,.via.pro3.slaughterhouse.ListA" +
      "nimalsResponse2\261\003\n\021AnimalPartService\022w\n\020" +
      "CreateAnimalPart\0220.via.pro3.slaughterhou" +
      "se.CreateAnimalPartRequest\0321.via.pro3.sl" +
      "aughterhouse.CreateAnimalPartResponse\022]\n" +
      "\rGetAnimalPart\022\'.via.pro3.slaughterhouse" +
      ".GetByIdRequest\032#.via.pro3.slaughterhous" +
      "e.AnimalPart\022g\n\020DeleteAnimalPart\022*.via.p" +
      "ro3.slaughterhouse.DeleteByIdRequest\032\'.v" +
      "ia.pro3.slaughterhouse.DeleteResponse\022[\n" +
      "\017ListAnimalParts\022\026.google.protobuf.Empty" +
      "\0320.via.pro3.slaughterhouse.ListAnimalPar" +
      "tsResponse2\373\002\n\013TrayService\022e\n\nCreateTray" +
      "\022*.via.pro3.slaughterhouse.CreateTrayReq" +
      "uest\032+.via.pro3.slaughterhouse.CreateTra" +
      "yResponse\022Q\n\007GetTray\022\'.via.pro3.slaughte" +
      "rhouse.GetByIdRequest\032\035.via.pro3.slaught" +
      "erhouse.Tray\022a\n\nDeleteTray\022*.via.pro3.sl" +
      "aughterhouse.DeleteByIdRequest\032\'.via.pro" +
      "3.slaughterhouse.DeleteResponse\022O\n\tListT" +
      "rays\022\026.google.protobuf.Empty\032*.via.pro3." +
      "slaughterhouse.ListTraysResponse2\226\003\n\016Pro" +
      "ductService\022n\n\rCreateProduct\022-.via.pro3." +
      "slaughterhouse.CreateProductRequest\032..vi" +
      "a.pro3.slaughterhouse.CreateProductRespo" +
      "nse\022W\n\nGetProduct\022\'.via.pro3.slaughterho" +
      "use.GetByIdRequest\032 .via.pro3.slaughterh" +
      "ouse.Product\022d\n\rDeleteProduct\022*.via.pro3" +
      ".slaughterhouse.DeleteByIdRequest\032\'.via." +
      "pro3.slaughterhouse.DeleteResponse\022U\n\014Li" +
      "stProducts\022\026.google.protobuf.Empty\032-.via" +
      ".pro3.slaughterhouse.ListProductsRespons" +
      "e2\313\003\n\024ProductToPartService\022\200\001\n\023CreatePro" +
      "ductToPart\0223.via.pro3.slaughterhouse.Cre" +
      "ateProductToPartRequest\0324.via.pro3.slaug" +
      "hterhouse.CreateProductToPartResponse\022c\n" +
      "\020GetProductToPart\022\'.via.pro3.slaughterho" +
      "use.GetByIdRequest\032&.via.pro3.slaughterh" +
      "ouse.ProductToPart\022j\n\023DeleteProductToPar" +
      "t\022*.via.pro3.slaughterhouse.DeleteByIdRe" +
      "quest\032\'.via.pro3.slaughterhouse.DeleteRe" +
      "sponse\022_\n\021ListProductToPart\022\026.google.pro" +
      "tobuf.Empty\0322.via.pro3.slaughterhouse.Li" +
      "stProductToPartResponseB0\n\027com.slaughter" +
      "house.grpcB\023SlaughterhouseProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_via_pro3_slaughterhouse_Animal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_pro3_slaughterhouse_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_Animal_descriptor,
        new java.lang.String[] { "Id", "RegistrationNumber", "Weight", "ArrivalTime", });
    internal_static_via_pro3_slaughterhouse_AnimalPart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_pro3_slaughterhouse_AnimalPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_AnimalPart_descriptor,
        new java.lang.String[] { "Id", "AnimalId", "PartType", "Weight", });
    internal_static_via_pro3_slaughterhouse_Tray_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_pro3_slaughterhouse_Tray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_Tray_descriptor,
        new java.lang.String[] { "Id", "PartType", "MaxWeight", });
    internal_static_via_pro3_slaughterhouse_Product_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_pro3_slaughterhouse_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_via_pro3_slaughterhouse_ProductToPart_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_via_pro3_slaughterhouse_ProductToPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ProductToPart_descriptor,
        new java.lang.String[] { "Id", "ProductId", "PartId", "Quantity", });
    internal_static_via_pro3_slaughterhouse_Error_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_via_pro3_slaughterhouse_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_Error_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_via_pro3_slaughterhouse_GetByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_via_pro3_slaughterhouse_GetByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_GetByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_pro3_slaughterhouse_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_via_pro3_slaughterhouse_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_DeleteResponse_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_descriptor,
        new java.lang.String[] { "Animal", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor,
        new java.lang.String[] { "Animal", "Error", });
    internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_descriptor,
        new java.lang.String[] { "Animals", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor,
        new java.lang.String[] { "Part", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_descriptor,
        new java.lang.String[] { "Part", "Error", });
    internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_descriptor,
        new java.lang.String[] { "Parts", });
    internal_static_via_pro3_slaughterhouse_CreateTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_via_pro3_slaughterhouse_CreateTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateTrayRequest_descriptor,
        new java.lang.String[] { "Tray", });
    internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_via_pro3_slaughterhouse_CreateTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor,
        new java.lang.String[] { "Tray", "Error", });
    internal_static_via_pro3_slaughterhouse_ListTraysResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_via_pro3_slaughterhouse_ListTraysResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListTraysResponse_descriptor,
        new java.lang.String[] { "Trays", });
    internal_static_via_pro3_slaughterhouse_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_via_pro3_slaughterhouse_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductRequest_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_via_pro3_slaughterhouse_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_via_pro3_slaughterhouse_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductResponse_descriptor,
        new java.lang.String[] { "Product", "Error", });
    internal_static_via_pro3_slaughterhouse_ListProductsResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_via_pro3_slaughterhouse_ListProductsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListProductsResponse_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_descriptor,
        new java.lang.String[] { "Mapping", });
    internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor,
        new java.lang.String[] { "Mapping", "Error", });
    internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor,
        new java.lang.String[] { "Mappings", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
