// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.slaughterhouse.grpc;

public final class SlaughterhouseProto {
  private SlaughterhouseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_AnimalProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_AnimalProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_AnimalPartProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_AnimalPartProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_TrayProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_TrayProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ProductProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ProductProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ProductToPartProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ProductToPartProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_GetByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_GetByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListTraysResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListTraysResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListProductsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListProductsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024slaughterhouse.proto\022\027via.pro3.slaught" +
      "erhouse\032\037google/protobuf/timestamp.proto" +
      "\032\033google/protobuf/empty.proto\"\210\001\n\013Animal" +
      "Proto\022\n\n\002id\030\001 \001(\005\022\033\n\023registration_number" +
      "\030\002 \001(\t\022\016\n\006weight\030\003 \001(\001\0220\n\014arrival_time\030\004" +
      " \001(\0132\032.google.protobuf.Timestamp\022\016\n\006orig" +
      "in\030\005 \001(\t\"S\n\017AnimalPartProto\022\n\n\002id\030\001 \001(\005\022" +
      "\021\n\tanimal_id\030\002 \001(\005\022\021\n\tpart_type\030\003 \001(\t\022\016\n" +
      "\006weight\030\004 \001(\001\">\n\tTrayProto\022\n\n\002id\030\001 \001(\005\022\021" +
      "\n\tpart_type\030\002 \001(\t\022\022\n\nmax_weight\030\003 \001(\001\"=\n" +
      "\014ProductProto\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022" +
      "\023\n\013description\030\003 \001(\t\"W\n\022ProductToPartPro" +
      "to\022\n\n\002id\030\001 \001(\005\022\022\n\nproduct_id\030\002 \001(\005\022\017\n\007pa" +
      "rt_id\030\003 \001(\005\022\020\n\010quantity\030\004 \001(\005\"&\n\005Error\022\014" +
      "\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"\034\n\016GetById" +
      "Request\022\n\n\002id\030\001 \001(\005\"\037\n\021DeleteByIdRequest" +
      "\022\n\n\002id\030\001 \001(\005\"?\n\016DeleteResponse\022-\n\005error\030" +
      "\001 \001(\0132\036.via.pro3.slaughterhouse.Error\"K\n" +
      "\023CreateAnimalRequest\0224\n\006animal\030\001 \001(\0132$.v" +
      "ia.pro3.slaughterhouse.AnimalProto\"{\n\024Cr" +
      "eateAnimalResponse\0224\n\006animal\030\001 \001(\0132$.via" +
      ".pro3.slaughterhouse.AnimalProto\022-\n\005erro" +
      "r\030\002 \001(\0132\036.via.pro3.slaughterhouse.Error\"" +
      "L\n\023ListAnimalsResponse\0225\n\007animals\030\001 \003(\0132" +
      "$.via.pro3.slaughterhouse.AnimalProto\"Q\n" +
      "\027CreateAnimalPartRequest\0226\n\004part\030\001 \001(\0132(" +
      ".via.pro3.slaughterhouse.AnimalPartProto" +
      "\"\201\001\n\030CreateAnimalPartResponse\0226\n\004part\030\001 " +
      "\001(\0132(.via.pro3.slaughterhouse.AnimalPart" +
      "Proto\022-\n\005error\030\002 \001(\0132\036.via.pro3.slaughte" +
      "rhouse.Error\"R\n\027ListAnimalPartsResponse\022" +
      "7\n\005parts\030\001 \003(\0132(.via.pro3.slaughterhouse" +
      ".AnimalPartProto\"E\n\021CreateTrayRequest\0220\n" +
      "\004tray\030\001 \001(\0132\".via.pro3.slaughterhouse.Tr" +
      "ayProto\"u\n\022CreateTrayResponse\0220\n\004tray\030\001 " +
      "\001(\0132\".via.pro3.slaughterhouse.TrayProto\022" +
      "-\n\005error\030\002 \001(\0132\036.via.pro3.slaughterhouse" +
      ".Error\"F\n\021ListTraysResponse\0221\n\005trays\030\001 \003" +
      "(\0132\".via.pro3.slaughterhouse.TrayProto\"N" +
      "\n\024CreateProductRequest\0226\n\007product\030\001 \001(\0132" +
      "%.via.pro3.slaughterhouse.ProductProto\"~" +
      "\n\025CreateProductResponse\0226\n\007product\030\001 \001(\013" +
      "2%.via.pro3.slaughterhouse.ProductProto\022" +
      "-\n\005error\030\002 \001(\0132\036.via.pro3.slaughterhouse" +
      ".Error\"O\n\024ListProductsResponse\0227\n\010produc" +
      "ts\030\001 \003(\0132%.via.pro3.slaughterhouse.Produ" +
      "ctProto\"Z\n\032CreateProductToPartRequest\022<\n" +
      "\007mapping\030\001 \001(\0132+.via.pro3.slaughterhouse" +
      ".ProductToPartProto\"\212\001\n\033CreateProductToP" +
      "artResponse\022<\n\007mapping\030\001 \001(\0132+.via.pro3." +
      "slaughterhouse.ProductToPartProto\022-\n\005err" +
      "or\030\002 \001(\0132\036.via.pro3.slaughterhouse.Error" +
      "\"Z\n\031ListProductToPartResponse\022=\n\010mapping" +
      "s\030\001 \003(\0132+.via.pro3.slaughterhouse.Produc" +
      "tToPartProto2\222\003\n\rAnimalService\022k\n\014Create" +
      "Animal\022,.via.pro3.slaughterhouse.CreateA" +
      "nimalRequest\032-.via.pro3.slaughterhouse.C" +
      "reateAnimalResponse\022Z\n\tGetAnimal\022\'.via.p" +
      "ro3.slaughterhouse.GetByIdRequest\032$.via." +
      "pro3.slaughterhouse.AnimalProto\022c\n\014Delet" +
      "eAnimal\022*.via.pro3.slaughterhouse.Delete" +
      "ByIdRequest\032\'.via.pro3.slaughterhouse.De" +
      "leteResponse\022S\n\013ListAnimals\022\026.google.pro" +
      "tobuf.Empty\032,.via.pro3.slaughterhouse.Li" +
      "stAnimalsResponse2\266\003\n\021AnimalPartService\022" +
      "w\n\020CreateAnimalPart\0220.via.pro3.slaughter" +
      "house.CreateAnimalPartRequest\0321.via.pro3" +
      ".slaughterhouse.CreateAnimalPartResponse" +
      "\022b\n\rGetAnimalPart\022\'.via.pro3.slaughterho" +
      "use.GetByIdRequest\032(.via.pro3.slaughterh" +
      "ouse.AnimalPartProto\022g\n\020DeleteAnimalPart" +
      "\022*.via.pro3.slaughterhouse.DeleteByIdReq" +
      "uest\032\'.via.pro3.slaughterhouse.DeleteRes" +
      "ponse\022[\n\017ListAnimalParts\022\026.google.protob" +
      "uf.Empty\0320.via.pro3.slaughterhouse.ListA" +
      "nimalPartsResponse2\200\003\n\013TrayService\022e\n\nCr" +
      "eateTray\022*.via.pro3.slaughterhouse.Creat" +
      "eTrayRequest\032+.via.pro3.slaughterhouse.C" +
      "reateTrayResponse\022V\n\007GetTray\022\'.via.pro3." +
      "slaughterhouse.GetByIdRequest\032\".via.pro3" +
      ".slaughterhouse.TrayProto\022a\n\nDeleteTray\022" +
      "*.via.pro3.slaughterhouse.DeleteByIdRequ" +
      "est\032\'.via.pro3.slaughterhouse.DeleteResp" +
      "onse\022O\n\tListTrays\022\026.google.protobuf.Empt" +
      "y\032*.via.pro3.slaughterhouse.ListTraysRes" +
      "ponse2\233\003\n\016ProductService\022n\n\rCreateProduc" +
      "t\022-.via.pro3.slaughterhouse.CreateProduc" +
      "tRequest\032..via.pro3.slaughterhouse.Creat" +
      "eProductResponse\022\\\n\nGetProduct\022\'.via.pro" +
      "3.slaughterhouse.GetByIdRequest\032%.via.pr" +
      "o3.slaughterhouse.ProductProto\022d\n\rDelete" +
      "Product\022*.via.pro3.slaughterhouse.Delete" +
      "ByIdRequest\032\'.via.pro3.slaughterhouse.De" +
      "leteResponse\022U\n\014ListProducts\022\026.google.pr" +
      "otobuf.Empty\032-.via.pro3.slaughterhouse.L" +
      "istProductsResponse2\320\003\n\024ProductToPartSer" +
      "vice\022\200\001\n\023CreateProductToPart\0223.via.pro3." +
      "slaughterhouse.CreateProductToPartReques" +
      "t\0324.via.pro3.slaughterhouse.CreateProduc" +
      "tToPartResponse\022h\n\020GetProductToPart\022\'.vi" +
      "a.pro3.slaughterhouse.GetByIdRequest\032+.v" +
      "ia.pro3.slaughterhouse.ProductToPartProt" +
      "o\022j\n\023DeleteProductToPart\022*.via.pro3.slau" +
      "ghterhouse.DeleteByIdRequest\032\'.via.pro3." +
      "slaughterhouse.DeleteResponse\022_\n\021ListPro" +
      "ductToPart\022\026.google.protobuf.Empty\0322.via" +
      ".pro3.slaughterhouse.ListProductToPartRe" +
      "sponseB0\n\027com.slaughterhouse.grpcB\023Slaug" +
      "hterhouseProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_via_pro3_slaughterhouse_AnimalProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_pro3_slaughterhouse_AnimalProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_AnimalProto_descriptor,
        new java.lang.String[] { "Id", "RegistrationNumber", "Weight", "ArrivalTime", "Origin", });
    internal_static_via_pro3_slaughterhouse_AnimalPartProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_pro3_slaughterhouse_AnimalPartProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_AnimalPartProto_descriptor,
        new java.lang.String[] { "Id", "AnimalId", "PartType", "Weight", });
    internal_static_via_pro3_slaughterhouse_TrayProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_pro3_slaughterhouse_TrayProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_TrayProto_descriptor,
        new java.lang.String[] { "Id", "PartType", "MaxWeight", });
    internal_static_via_pro3_slaughterhouse_ProductProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_pro3_slaughterhouse_ProductProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ProductProto_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_via_pro3_slaughterhouse_ProductToPartProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_via_pro3_slaughterhouse_ProductToPartProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ProductToPartProto_descriptor,
        new java.lang.String[] { "Id", "ProductId", "PartId", "Quantity", });
    internal_static_via_pro3_slaughterhouse_Error_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_via_pro3_slaughterhouse_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_Error_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_via_pro3_slaughterhouse_GetByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_via_pro3_slaughterhouse_GetByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_GetByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_DeleteByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_pro3_slaughterhouse_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_via_pro3_slaughterhouse_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_DeleteResponse_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalRequest_descriptor,
        new java.lang.String[] { "Animal", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalResponse_descriptor,
        new java.lang.String[] { "Animal", "Error", });
    internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListAnimalsResponse_descriptor,
        new java.lang.String[] { "Animals", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalPartRequest_descriptor,
        new java.lang.String[] { "Part", });
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateAnimalPartResponse_descriptor,
        new java.lang.String[] { "Part", "Error", });
    internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListAnimalPartsResponse_descriptor,
        new java.lang.String[] { "Parts", });
    internal_static_via_pro3_slaughterhouse_CreateTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_via_pro3_slaughterhouse_CreateTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateTrayRequest_descriptor,
        new java.lang.String[] { "Tray", });
    internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_via_pro3_slaughterhouse_CreateTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateTrayResponse_descriptor,
        new java.lang.String[] { "Tray", "Error", });
    internal_static_via_pro3_slaughterhouse_ListTraysResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_via_pro3_slaughterhouse_ListTraysResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListTraysResponse_descriptor,
        new java.lang.String[] { "Trays", });
    internal_static_via_pro3_slaughterhouse_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_via_pro3_slaughterhouse_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductRequest_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_via_pro3_slaughterhouse_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_via_pro3_slaughterhouse_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductResponse_descriptor,
        new java.lang.String[] { "Product", "Error", });
    internal_static_via_pro3_slaughterhouse_ListProductsResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_via_pro3_slaughterhouse_ListProductsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListProductsResponse_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductToPartRequest_descriptor,
        new java.lang.String[] { "Mapping", });
    internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_CreateProductToPartResponse_descriptor,
        new java.lang.String[] { "Mapping", "Error", });
    internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_pro3_slaughterhouse_ListProductToPartResponse_descriptor,
        new java.lang.String[] { "Mappings", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
